# Generated by Django 4.1.2 on 2022-11-04 17:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('street_name', models.TextField()),
                ('district', models.TextField()),
                ('number', models.IntegerField()),
                ('zip_code', models.CharField(max_length=8)),
                ('city', models.TextField()),
                ('state', models.CharField(max_length=2)),
                ('address_complement', models.TextField()),
            ],
        ),
    ]
