# Generated by Django 4.1.2 on 2022-11-07 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authors", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="name",
            field=models.CharField(max_length=127, unique=True),
        ),
    ]
