# Generated by Django 4.1.2 on 2022-11-04 17:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=126)),
                ('date_release', models.DateField()),
                ('book_cover', models.URLField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField()),
                ('publishing_company', models.CharField(max_length=126)),
                ('language', models.CharField(max_length=50)),
                ('edition_number', models.CharField(max_length=50)),
                ('number_pages', models.IntegerField()),
                ('country', models.CharField(max_length=50)),
                ('isbn', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(13)])),
                ('type', models.CharField(choices=[('E-book', 'Ebook'), ('Book', 'Book')], default='E-book', max_length=7)),
                ('amount', models.PositiveIntegerField(default=1)),
                ('weigth', models.PositiveIntegerField(default=0)),
                ('format', models.PositiveIntegerField(default=0)),
                ('length', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('width', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('diameter', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='authors.author')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='categories.categories')),
            ],
        ),
    ]
