# Generated by Django 4.1.2 on 2022-11-04 17:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Order created', 'Order Created'), ('Process payment', 'Process Payment'), ('Authorized payment', 'Authorized Payment'), ('Waiting Shipping', 'Waiting Shipping'), ('Sent', 'Sent'), ('Order completed', 'Order Completed')], default='Order created', max_length=40)),
                ('shipping', models.IntegerField()),
                ('ammount_items', models.IntegerField()),
                ('total_value', models.IntegerField()),
            ],
        ),
    ]
