# Generated by Django 4.1.2 on 2022-11-07 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="books_id",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
